
[functions.send-interview-reminders]
enabled = true
verify_jwt = true
import_map = "./functions/send-interview-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-interview-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-interview-reminders/*.html" ]

[functions.send-monthly-digest]
enabled = true
verify_jwt = true
import_map = "./functions/send-monthly-digest/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-monthly-digest/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-monthly-digest/*.html" ]
